### ISSUE TITLE
Build process not documented & configuration incomplete?

### ISSUE THREAD

**Issue by follower** [ankitkaushal/nzip#2]
Hi,

I really appreciated being able to download the `nzip.jar` file without needing to build anything.

However, while trying to recreate `nzip.jar` to fix #1 I discovered that there is no build documentation and the maven `pom.xml` file appears to be incomplete?

Primarily the issues I encountered were:

 0) Need to install maven.
 1) Need to update some dependency versions.
 2) Need to configure the built jar main class.
 3) Need to configure the dependencies to be included in the jar.

I eventually managed to hack something together which I might end up pushing to my fork but if you have a fully functioning configuration already, perhaps you could commit it?

Thanks!

**Comment by ankitkaushal** [comment]
You can use java 6 and maven to compile the project. For building it, I think I exported it as a runnable jar using eclipse. If you import it as a maven project in Intellij or eclipse it will compile automatically.

**Comment by ankitkaushal** [comment]
I have added the step to automatically make jar with maven
